network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eth0:
      dhcp4: true
      optional: true
  wifis:
    wlan0:
      addresses: [192.168.10.50/24]
      access-points:
        "BuoyAP":
          password: "drone@12"
          mode: ap
